theme: jekyll-theme-minimal
title: 'PsyComp Lab'
description: '<p style="text-align:left">@ Computer Science Department & Psychology Department, Sapienza University of Rome</p>'
logo: /imgs/logo.png
show_downloads: false
